

/* Called once after the target application is downloaded. */
execUserSetup()
{
    /* Re-load secure image partially erased by IAR reset */
	__loadImage("$EXE_DIR$\\..\\..\\..\\AppliNonSecure\\RIF_Peripheral_NS\\Exe\\RIF_Peripheral_AppliNonSecure_NS.out", 0, 0);
    __loadImage("$EXE_DIR$\\RIF_Peripheral_FSBL.out", 0, 0);

    __restoreSoftwareBreakpoints();

    #PC = __readMemory32(0x34180404, "Memory");
    #SP = __readMemory32(0x34180400, "Memory");
}
