/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeMX
 * @brief     Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib or Picolibc libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>

/* Driver API */
#include "Common/Inc/Init/syscalls.h"
#include "Common/Inc/Init/app_filex.h"

/* Variables */

/* -------------------------------------------------------------
 * Konfiguration
 * -----------------------------------------------------------*/

#ifndef FILEX_MAX_FDS
#define FILEX_MAX_FDS   16      /* max. Anzahl FileX-basierter FDs */
#endif

#ifndef FILEX_FIRST_FD
#define FILEX_FIRST_FD   3      /* 0,1,2 = stdin, stdout, stderr */
#endif

/* Timeout für Mutex-Zugriffe */
#ifndef FILEX_MUTEX_WAIT
#define FILEX_MUTEX_WAIT TX_WAIT_FOREVER
#endif

static_assert(FILEX_MAX_FDS < NX_BSD_SOCKFD_START, "FileX descriptors must be below sockets FDs");
static_assert(NX_BSD_SOCKFD_START >= 32, "invalid value for first BSD socket fd");

/* -------------------------------------------------------------
 * Globale Variablen
 * -----------------------------------------------------------*/

/* ThreadX-Mutex zum Schutz von FileX */
static TX_MUTEX g_filex_fs_mutex;

/* Eintrag in der FD-Tabelle */
typedef struct {
	FX_MEDIA *media;
    FX_FILE file;
    int     in_use;
    int     flags;     /* O_RDONLY/O_WRONLY/O_RDWR/... */
    char    name[FX_MAX_LONG_NAME_LEN + 1]; /* Name, z.B. für SEEK_END */
} filex_fd_t;

static filex_fd_t g_fd_table[FILEX_MAX_FDS];

static TX_MUTEX sys_lock_read;		// _read
static TX_MUTEX sys_lock_write;		// _write
static bool init_sys_lock_read = false;
static bool init_sys_lock_write = false;

/* -------------------------------------------------------------
 * Initialisierung
 * -----------------------------------------------------------*/

/*
 * Muss vom Applikationscode EINMALIG aufgerufen werden, nachdem
 *  - ThreadX gestartet und
 *  - FileX/Medium initialisiert ist.
 */
UINT filex_newlib_init(void)
{
    UINT status;

    status = tx_mutex_create(&g_filex_fs_mutex, "newlib_fs_mutex", TX_INHERIT);
    if (status != TX_SUCCESS) {
        return status;
    }

    /* FD-Tabelle zurücksetzen */
    memset(g_fd_table, 0x00, sizeof(g_fd_table));

    // Init mutexes for printf to linearize
    tx_mutex_create(&sys_lock_read, (CHAR*)"sys_lock_read", TX_INHERIT);
    tx_mutex_create(&sys_lock_write, (CHAR*)"sys_lock_write", TX_INHERIT);
    init_sys_lock_read = true;
    init_sys_lock_write = true;
    printf("Newlib: Init clib layer done.\n");
    return FX_SUCCESS;
}


/* -------------------------------------------------------------
 * Hilfsfunktionen
 * -----------------------------------------------------------*/

static int alloc_fd(void)
{
    for (int i = FILEX_FIRST_FD; i < FILEX_MAX_FDS; ++i) {
        if (!g_fd_table[i].in_use) {
            g_fd_table[i].in_use = 1;
            return i;
        }
    }
    return -1;
}

static void free_fd(int fd)
{
    if (fd >= FILEX_FIRST_FD && fd < FILEX_MAX_FDS) {
        g_fd_table[fd].in_use = 0;
        g_fd_table[fd].flags  = 0;
        g_fd_table[fd].name[0] = '\0';
    }
}

static int lock_fs(void)
{
    if (tx_mutex_get(&g_filex_fs_mutex, FILEX_MUTEX_WAIT) != TX_SUCCESS) {
        errno = EBUSY;
        return -1;
    }
    return 0;
}

static void unlock_fs(void)
{
    tx_mutex_put(&g_filex_fs_mutex);
}

/**
  * @brief  Retargets the C library printf function to the USART.
  * @param  None
  * @retval None
  */
int __io_putchar(int ch)
{
    if (ch == '\n') {
        uint8_t crlf[2] = {'\r','\n'};
        syscall_HAL_UART_write(crlf,2);
        return ch;
    }

  /* Place your implementation of putchar here */
  /* e.g. write a character to the USART1 and Loop until the end of transmission */
  syscall_HAL_UART_write( (uint8_t *) &ch, 1);
  return ch;
}

int __io_getchar(void)
{
	int ch;

	syscall_HAL_UART_read((uint8_t *)&ch);
	return ch;
}

char *__env[1] = { 0 };
char **environ = __env;


/* Functions */
void initialise_monitor_handles()
{
}

int _getpid(void)
{
  return 1;
}

int _kill(int pid, int sig)
{
  (void)pid;
  (void)sig;
  errno = EINVAL;
  return -1;
}

void _exit (int status)
{
  _kill(status, -1);
  while (1) {}    /* Make sure we hang here */
}

ssize_t _read(int fd, void *buf, size_t len)
{
  /* stdin/stdout/stderr -> hier z.B. auf UART routen */
  if (fd >= 0 && fd < FILEX_FIRST_FD) {
	  char * char_ptr = (char *) buf;

	  switch(fd)
	  {
	  case STDIN_FILENO:
		  if(init_sys_lock_read == true) tx_mutex_get(&sys_lock_read, TX_WAIT_FOREVER);
		  for (int iter = 0; iter < len; iter++)
		  {
			  *char_ptr++ = __io_getchar();
		  }
		  if(init_sys_lock_read == true) tx_mutex_put(&sys_lock_read);
		  return (ssize_t)len;
	  default:
		  return (ssize_t)-1;
	  }
  }


  if (fd >= FILEX_MAX_FDS || !g_fd_table[fd].in_use) {
      errno = EBADF;
      return -1;
  }

  //printf("Newlib: _read %d %p, %d\n", fd, buf, len);

  if (lock_fs() < 0) {
      return -1;
  }

  filex_fd_t *entry = &g_fd_table[fd];
  FX_FILE    *fx    = &entry->file;

  if (entry->media == NULL || buf == NULL) {
      errno = EINVAL;
      return -1;
  }

  ULONG bytes_read = 0;
  UINT  status     = fx_file_read(fx, buf, (ULONG)len, &bytes_read);

  unlock_fs();

  if ((status != FX_SUCCESS) && (status != FX_END_OF_FILE)) {
      errno = EIO;
      return -1;
  }

  return (ssize_t)bytes_read;
}

ssize_t _write(int fd, const void *buf, size_t len)
{
  /* stdin/stdout/stderr -> hier z.B. auf UART routen */
  if (fd >= 0 && fd < FILEX_FIRST_FD) {
	  char * char_ptr = (char *) buf;

	  switch(fd)
	  {
	  case STDOUT_FILENO:
	  case STDERR_FILENO:
		  if(init_sys_lock_write == true) tx_mutex_get(&sys_lock_write, TX_WAIT_FOREVER);
		  for (int iter = 0; iter < len; iter++)
		  {
		    __io_putchar(*char_ptr++);
		  }
		  if(init_sys_lock_write == true) tx_mutex_put(&sys_lock_write);
		  return (ssize_t)len;
	  default:
		  return (ssize_t)-1;
	  }
  }

  // Recursive Call to _write !!
  //printf("Newlib: _write %d %p, %d\n", fd, buf, len);

  if (fd < FILEX_FIRST_FD || fd >= FILEX_MAX_FDS || !g_fd_table[fd].in_use) {
      errno = EBADF;
      return -1;
  }

  if (lock_fs() < 0) {
      return -1;
  }

  filex_fd_t *entry = &g_fd_table[fd];
  FX_FILE    *fx    = &entry->file;

  if (entry->media == NULL || buf == NULL) {
      errno = EINVAL;
      return -1;
  }

  /* FileX schreibt i.d.R. ganz oder gar nicht */
  UINT status = fx_file_write(fx, (VOID *)buf, (ULONG)len);

  /* optional: flush hier oder erst beim close */
  /* fx_media_flush(entry->media); */

  unlock_fs();

  if (status != FX_SUCCESS) {
      errno = EIO;
      return -1;
  }

  return (ssize_t)len;
}

int _close(int fd)
{
  //printf("_close: fd=%d\n", file);

  // Check if fd belongs to BSD socket API
  if(fd >= NX_BSD_SOCKFD_START)
  {
	  // call socket close handler
	  return syscall_close_socket(fd);
  }

  if (fd < FILEX_FIRST_FD || fd >= FILEX_MAX_FDS || !g_fd_table[fd].in_use) {
	  errno = EBADF;
	  return -1;
  }

  //printf("Newlib: _close %d\n", fd);

  if (lock_fs() < 0) {
	  return -1;
  }

  filex_fd_t *entry = &g_fd_table[fd];

  if (entry->media == NULL) {
	  errno = EINVAL;
	  return -1;
  }

  UINT status = fx_file_close(&entry->file);

  if (status == FX_SUCCESS) {
	  /* Medium flushen, um Daten sicher wegzuschreiben */
	  fx_media_flush(entry->media);
	  free_fd(fd);
	  unlock_fs();
	  return 0;
  } else {
	  unlock_fs();
	  errno = EIO;
	  return -1;
  }
}

/*
 * _isatty
 *
 * stdin/stdout/stderr -> TTY
 */
int _isatty(int fd)
{
    if (fd >= 0 && fd < FILEX_FIRST_FD)
        return 1;
    return 0;
}

/*
 * _lseek
 *
 * Einfache Implementierung:
 *  - Unterstützt SEEK_SET und SEEK_CUR
 *  - SEEK_END kann bei Bedarf erweitert werden
 */
#define off_t int
off_t _lseek(int fd, off_t offset, int whence)
{
    if (fd < FILEX_FIRST_FD || fd >= FILEX_MAX_FDS || !g_fd_table[fd].in_use) {
        errno = EBADF;
        return -1;
    }

	//printf("Newlib: _lseek %d %d, %d\n", fd, offset, whence);

    if (lock_fs() < 0) {
        return -1;
    }

    filex_fd_t *entry = &g_fd_table[fd];

    if (entry->media == NULL) {
        errno = EINVAL;
        return -1;
    }

    FX_FILE    *fx    = &entry->file;
    UINT status;
    ULONG new_pos;

    switch (whence) {
    case SEEK_SET:
        status = fx_file_seek(fx, (ULONG)offset);
        new_pos = (ULONG)offset;
        break;

    case SEEK_CUR: {
        /* aktuelle Position + offset */
        ULONG current;
        /* FileX speichert aktuelle Position in file_current_file_offset */
        /* Achtung: Struktur ist intern – je nach Version kann sich das ändern.
         * Alternativ könnte man eine eigene Positionsverwaltung pflegen.
         */
        current = fx->fx_file_current_file_offset;
        new_pos = current + (LONG)offset;
        status  = fx_file_seek(fx, new_pos);
        break;
    }

    case SEEK_END: {
        /* Optional: Dateigröße über directory_information_get holen */
        ULONG size;
        UINT attributes, year, month, day, hour, minute, second;

        status = fx_directory_information_get(
                     entry->media,
                     (CHAR *)entry->name,
                     &attributes,
                     &size,
                     &year,
                     &month,
                     &day,
                     &hour,
                     &minute,
                     &second
                 );
        if (status != FX_SUCCESS) {
            unlock_fs();
            errno = EIO;
            return -1;
        }

        LONG pos = (LONG)size + (LONG)offset;
        if (pos < 0) {
            unlock_fs();
            errno = EINVAL;
            return -1;
        }

        new_pos = (ULONG)pos;
        status  = fx_file_seek(fx, new_pos);
        break;
    }

    default:
        unlock_fs();
        errno = EINVAL;
        return -1;
    }

    unlock_fs();

    if (status != FX_SUCCESS) {
        errno = EINVAL;
        return -1;
    }

    return (off_t)new_pos;
}

/*
 * _open
 *
 * Wandelt open()-Flags in FileX-Operationen um:
 *  - O_CREAT -> fx_file_create
 *  - O_TRUNC -> vorhandene Datei löschen
 *  - O_APPEND -> ans Dateiende seeken
 */
int _open(const char *name, int flags, int mode)
{
	//char filename[FILEX_FILENAME_SIZE];

    (void)mode; /* Mode wird im Embedded-Kontext oft ignoriert */

	//printf("Newlib: _open %s %d %d\n", name, flags, mode);

    if (name == NULL) {
        errno = EINVAL;
        return -1;
    }

    if (lock_fs() < 0) {
        return -1;
    }

    int fd = alloc_fd();
    if (fd < 0) {
        unlock_fs();
        errno = EMFILE; /* zu viele offene Dateien */
        return -1;
    }

    filex_fd_t *entry = &g_fd_table[fd];
    FX_FILE    *fx    = &entry->file;
    UINT        status;

    /* media pointer bestimmen */
    /* Dateiname merken (für spätere directory_information_get/SEEK_END) */
    MX_FileX_Eval_Path(name, &entry->media, entry->name, sizeof(entry->name));
    if(entry->media == NULL)
    {
        free_fd(fd);
        unlock_fs();
    	return -1;
    }
    //printf("_open: %p %s\n", entry->media, entry->name);
    entry->flags = flags;

    /* Datei ggf. erzeugen */
    if (flags & O_CREAT) {

        if (flags & O_TRUNC) {
            /* Vorhandene Datei löschen – Fehler ignorieren, falls nicht existiert */
            fx_file_delete(entry->media, (CHAR *)entry->name);
        }

        status = fx_file_create(entry->media, (CHAR *)entry->name);

        /* Wenn Datei schon existiert und O_EXCL gesetzt ist -> Fehler */
        if (status == FX_ALREADY_CREATED && (flags & O_EXCL)) {
            free_fd(fd);
            unlock_fs();
            errno = EEXIST;
            return -1;
        }

        /* andere Fehler */
        if ((status != FX_SUCCESS) && (status != FX_ALREADY_CREATED)) {
            free_fd(fd);
            unlock_fs();
            errno = EIO;
            return -1;
        }
    }

    /* Öffnungsmodus */
    UINT open_mode = FX_OPEN_FOR_READ;
    if ((flags & O_WRONLY) || (flags & O_RDWR)) {
        open_mode |= FX_OPEN_FOR_WRITE;
    }

    status = fx_file_open(entry->media, fx, (CHAR *)entry->name, open_mode);
    if (status != FX_SUCCESS) {
        free_fd(fd);
        unlock_fs();
        errno = EIO;
        return -1;
    }

    /* Falls O_TRUNC und nicht bereits gelöscht: Datei auf Länge 0 kürzen */
    if ((flags & O_TRUNC) && !(flags & O_CREAT)) {
        status = fx_file_truncate(fx, 0);
        if (status != FX_SUCCESS) {
            fx_file_close(fx);
            free_fd(fd);
            unlock_fs();
            errno = EIO;
            return -1;
        }
    }

    /* Anhängen: ans Dateiende seeken */
    if (flags & O_APPEND) {
        ULONG size;
        UINT attributes, year, month, day, hour, minute, second;

        status = fx_directory_information_get(
                     entry->media,
                     (CHAR *)entry->name,
                     &attributes,
                     &size,
                     &year,
                     &month,
                     &day,
                     &hour,
                     &minute,
                     &second
                 );

        if (status == FX_SUCCESS) {
            /* size = Dateigröße in Bytes */
            status = fx_file_seek(fx, size);
        }

        if (status != FX_SUCCESS) {
            fx_file_close(fx);
            free_fd(fd);
            unlock_fs();
            errno = EIO;
            return -1;
        }
    }

    unlock_fs();
    return fd;
}

int _wait(int *status)
{
  (void)status;
  errno = ECHILD;
  return -1;
}

int _unlink(char *name)
{
  (void)name;
  errno = ENOENT;
  return -1;
}

int _link(char *old, char *new)
{
  (void)old;
  (void)new;
  errno = EMLINK;
  return -1;
}

int _fork(void)
{
  errno = EAGAIN;
  return -1;
}

int _execve(char *name, char **argv, char **env)
{
  (void)name;
  (void)argv;
  (void)env;
  errno = ENOMEM;
  return -1;
}

// --- Picolibc Specific Section ---
#if defined(__PICOLIBC__)

/**
 * @brief Picolibc helper function to output a character to a FILE stream.
 *        This redirects the output to the low-level __io_putchar function.
 * @param c Character to write.
 * @param file FILE stream pointer (ignored).
 * @retval int The character written.
 */
static int starm_putc(char c, FILE *file)
{
	(void) file;
  __io_putchar(c);
	return c;
}

/**
 * @brief Picolibc helper function to input a character from a FILE stream.
 *        This redirects the input from the low-level __io_getchar function.
 * @param file FILE stream pointer (ignored).
 * @retval int The character read, cast to an unsigned char then int.
 */
static int starm_getc(FILE *file)
{
	unsigned char c;
	(void) file;
  c = __io_getchar();
	return c;
}

// Define and initialize the standard I/O streams for Picolibc.
// FDEV_SETUP_STREAM connects the starm_putc and starm_getc helper functions to a FILE structure.
// _FDEV_SETUP_RW indicates the stream is for reading and writing.
static FILE __stdio = FDEV_SETUP_STREAM(starm_putc,
					starm_getc,
					NULL,
					_FDEV_SETUP_RW);

// Assign the standard stream pointers (stdin, stdout, stderr) to the initialized stream.
// Picolibc uses these pointers for standard I/O operations (printf, scanf, etc.).
FILE *const stdin = &__stdio;
__strong_reference(stdin, stdout);
__strong_reference(stdin, stderr);

// Create strong aliases mapping standard C library function names (without underscore)
// to the implemented system call stubs (with underscore). Picolibc uses these
// standard names internally, so this linking is required.
__strong_reference(_read, read);
__strong_reference(_write, write);
__strong_reference(_times, times);
__strong_reference(_execve, execve);
__strong_reference(_fork, fork);
__strong_reference(_link, link);
__strong_reference(_unlink, unlink);
__strong_reference(_stat, stat);
__strong_reference(_wait, wait);
__strong_reference(_open, open);
__strong_reference(_close, close);
__strong_reference(_lseek, lseek);
__strong_reference(_isatty, isatty);
__strong_reference(_fstat, fstat);
__strong_reference(_exit, exit);
__strong_reference(_kill, kill);
__strong_reference(_getpid, getpid);

#endif //__PICOLIBC__
