/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeMX
 * @brief     Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib or Picolibc libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <sys/types.h>
#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <signal.h>
#include <time.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/time.h>
#include <sys/times.h>

/* Driver API */
#include "Common/Inc/Init/syscalls.h"

/* Variables */

/* -------------------------------------------------------------
 * Konfiguration
 * -----------------------------------------------------------*/

/* -------------------------------------------------------------
 * Globale Variablen
 * -----------------------------------------------------------*/

/* -------------------------------------------------------------
 * Initialisierung
 * -----------------------------------------------------------*/

/*
 * _fstat
 *
 * Minimal-Implementierung: alles als reguläre Datei behandeln.
 */
int _fstat(int fd, struct stat *st)
{
    if (st == NULL) {
        errno = EINVAL;
        return -1;
    }

#if 0
    /* stdin/stdout/stderr als Char-Gerät */
    if (fd >= 0 && fd < FILEX_FIRST_FD) {
        st->st_mode = S_IFCHR;
        return 0;
    }
#endif
	//printf("Newlib: _fstat %d %p\n", fd, st);

    /* Rest als reguläre Datei */
    st->st_mode = S_IFREG;
    return 0;
}

clock_t _times(struct tms *buf)
{
  (void)buf;
  return -1;
}

int _stat(const char *file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}
