/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeMX
 * @brief     Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib or Picolibc libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>

#if PROJECT_OS_USE_BSD_SOCKETS == 1
#include "nxd_bsd.h"
#endif

/* Driver API */
#include "Common/Inc/Init/syscalls.h"

/* Variables */

/* -------------------------------------------------------------
 * Konfiguration
 * -----------------------------------------------------------*/

/* -------------------------------------------------------------
 * Globale Variablen
 * -----------------------------------------------------------*/

/* -------------------------------------------------------------
 * Initialisierung
 * -----------------------------------------------------------*/

int syscall_close_socket(int fd)
{
#if PROJECT_OS_USE_BSD_SOCKETS == 1
	return nx_bsd_soc_close(fd);
#else
	return 0;
#endif
}
