/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeMX
 * @brief     Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib or Picolibc libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */

/* Driver API */
#include "stm32n6xx_hal.h"
#include "BSP/Inc/stm32_dev_handles.h"
#include "Common/Inc/Init/syscalls.h"
#include "BSP/Inc/usart.h"

/* Variables */

/* -------------------------------------------------------------
 * Konfiguration
 * -----------------------------------------------------------*/

/* -------------------------------------------------------------
 * Globale Variablen
 * -----------------------------------------------------------*/

/* -------------------------------------------------------------
 * Initialisierung
 * -----------------------------------------------------------*/

/* -------------------------------------------------------------
 * Hilfsfunktionen
 * -----------------------------------------------------------*/

void syscall_HAL_UART_write(uint8_t * data, uint16_t len)
{
	UART_HandleTypeDef * hUsart = DebugUsartHandle_get();

	HAL_UART_Transmit(hUsart, data, len, HAL_MAX_DELAY);
}

void syscall_HAL_UART_read(uint8_t * data)
{
	UART_HandleTypeDef * hUsart = DebugUsartHandle_get();

	HAL_UART_Receive(hUsart, data, 1, HAL_MAX_DELAY);
}

#if PROJECT_PREMAIN_SERIAL_CONSOLE == 1
typedef void (*init_fptr_t)(void);
static void syscall_write_console_premain(void) {
  // läuft sehr früh, vor init_array
	MX_USART_ConsoleDeviceInit();
	syscall_HAL_UART_write((uint8_t *) "premain console enabled\r\n", 25);
}

__attribute__((used, section(".preinit_array")))
static init_fptr_t pf_syscall_write_console_premain = syscall_write_console_premain;
#endif

