/**
 ******************************************************************************
 * @file      wait_for_debugger.c
 * @author    Auto-generated by STM32CubeMX
 * @brief     Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib or Picolibc libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <stdbool.h>
#include "Common/Inc/Init/wait_for_debugger.h"

/* -------------------------------------------------------------
 * Konfiguration
 * -----------------------------------------------------------*/

/* -------------------------------------------------------------
 * Globale Variablen
 * -----------------------------------------------------------*/
#if defined(WAIT_FOR_DEBUGGER_IN_MAIN) || defined(WAIT_FOR_DEBUGGER_IN_INIT_THREAD)

bool sWaitForDebugger = true;

/* -------------------------------------------------------------
 * Initialisierung
 * -----------------------------------------------------------*/

/* -------------------------------------------------------------
 * Hilfsfunktionen
 * -----------------------------------------------------------*/

bool wait_for_debugger(bool wait)
{
	return wait;
}

#endif
