/**
 ******************************************************************************
 * @file      wait_for_debugger.c
 * @author    Auto-generated by STM32CubeMX
 * @brief     Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib or Picolibc libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <stdio.h>

#include "Common/Inc/Test/exception_stack_test/exception_stack_test.h"

/* -------------------------------------------------------------
 * Konfiguration
 * -----------------------------------------------------------*/

/* -------------------------------------------------------------
 * Globale Variablen
 * -----------------------------------------------------------*/

/* -------------------------------------------------------------
 * Initialisierung
 * -----------------------------------------------------------*/

/* -------------------------------------------------------------
 * Hilfsfunktionen
 * -----------------------------------------------------------*/

void exception_stack_test_level1()
{
	printf("Test: exception_stack_test_level1\n");
	// Call next level
	exception_stack_test_level2();
}
