#!/usr/bin/env bash
set -euo pipefail

# (c) Chad 2026

ALIGN=256

usage() {
  cat <<'EOF'
Usage:
  pack_bins.sh -l LIST.txt -o OUT.bin -H OUT.h

Options:
  -l  List file (one binary path per line; supports comments with #)
  -o  Output binary
  -H  Output C header
  -a  Alignment (default 256)

List file format:
  - One file per line
  - Empty lines ignored
  - Lines starting with # ignored
  - Inline comments allowed: "path/to/file.bin  # comment"
  - Relative paths are resolved relative to the list file location

Example:
  ./pack_bins.sh -l assets.list -o assets.bin -H assets.h
EOF
}

OUT_BIN=""
OUT_H=""
LIST_FILE=""

while getopts ":l:o:H:a:h" opt; do
  case "$opt" in
    l) LIST_FILE="$OPTARG" ;;
    o) OUT_BIN="$OPTARG" ;;
    H) OUT_H="$OPTARG" ;;
    a) ALIGN="$OPTARG" ;;
    h) usage; exit 0 ;;
    \?) echo "Unknown option: -$OPTARG" >&2; usage; exit 2 ;;
    :)  echo "Missing argument for -$OPTARG" >&2; usage; exit 2 ;;
  esac
done
shift $((OPTIND-1))

if [[ -z "${LIST_FILE}" || -z "${OUT_BIN}" || -z "${OUT_H}" || "$#" -ne 0 ]]; then
  usage >&2
  exit 2
fi

if [[ ! -f "$LIST_FILE" ]]; then
  echo "List file not found: $LIST_FILE" >&2
  exit 1
fi

# validate ALIGN
if ! [[ "$ALIGN" =~ ^[0-9]+$ ]] || [[ "$ALIGN" -le 0 ]]; then
  echo "Alignment must be a positive integer" >&2
  exit 2
fi

# --- helpers ---
to_ident() {
  local s
  s="$(basename "$1")"
  s="${s%.*}"
  s="${s//[^a-zA-Z0-9_]/_}"
  [[ "$s" =~ ^[0-9] ]] && s="_$s"
  printf "%s" "$s"
}

round_up() {
  local x="$1" a="$2"
  echo $(( (x + a - 1) / a * a ))
}

# resolve relative paths relative to list file directory
LIST_DIR="$(cd "$(dirname "$LIST_FILE")" && pwd -P)"

# --- init outputs ---
: > "$OUT_BIN"
tmp_h="$(mktemp)"
trap 'rm -f "$tmp_h"' EXIT

{
  echo "/* Autogenerated by pack_bins.sh */"
  echo "#pragma once"
  echo ""
  echo "#include <stddef.h>"
  echo "#include <stdint.h>"
  echo ""
  echo "#define PACK_ALIGN (${ALIGN}u)"
  echo ""
} > "$tmp_h"

offset=0
count=0

# Read list file line-by-line safely (preserve spaces)
# - Strip inline comments
# - Trim whitespace
while IFS= read -r line || [[ -n "$line" ]]; do
  # remove leading/trailing whitespace
  line="${line#"${line%%[![:space:]]*}"}"
  line="${line%"${line##*[![:space:]]}"}"

  # ignore empty lines / full-line comments
  [[ -z "$line" ]] && continue
  [[ "$line" == \#* ]] && continue

  # strip inline comments: everything after first unescaped '#'
  # (simple/typical case: "file.bin # comment")
  line="${line%%#*}"
  line="${line%"${line##*[![:space:]]}"}"
  [[ -z "$line" ]] && continue

  f="$line"
  if [[ "$f" != /* ]]; then
    f="$LIST_DIR/$f"
  fi

  if [[ ! -f "$f" ]]; then
    echo "Input not found (from list): $f" >&2
    exit 1
  fi

  size="$(stat -c%s "$f")"
  ident="$(to_ident "$f")"

  aligned_offset="$(round_up "$offset" "$ALIGN")"
  pad=$(( aligned_offset - offset ))
  if (( pad > 0 )); then
    dd if=/dev/zero bs=1 count="$pad" status=none >> "$OUT_BIN"
    offset="$aligned_offset"
  fi

  cat "$f" >> "$OUT_BIN"

  {
    echo "#define ${ident}_OFFSET (0x$(printf '%08X' "$offset")u)"
    echo "#define ${ident}_LENGTH (0x$(printf '%08X' "$size")u)"
    echo ""
  } >> "$tmp_h"

  offset=$(( offset + size ))
  count=$(( count + 1 ))
done < "$LIST_FILE"

if (( count == 0 )); then
  echo "No input files found in list: $LIST_FILE" >&2
  exit 1
fi

# optional: align total size
final_aligned="$(round_up "$offset" "$ALIGN")"
final_pad=$(( final_aligned - offset ))
if (( final_pad > 0 )); then
  dd if=/dev/zero bs=1 count="$final_pad" status=none >> "$OUT_BIN"
  offset="$final_aligned"
fi

{
  echo "#define PACK_TOTAL_SIZE (0x$(printf '%08X' "$offset")u)"
  echo "#define PACK_FILE_COUNT (${count}u)"
} >> "$tmp_h"

mv "$tmp_h" "$OUT_H"

echo "Wrote:"
echo "  $OUT_BIN (size: $(stat -c%s "$OUT_BIN") bytes)"
echo "  $OUT_H"
echo "  Inputs: $count"

