/*
 * Copyright (c) 2019, Arm Limited. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */
#include "region_defs.h"
#include "mcuboot_config/mcuboot_config.h"

#define _HEX(n) 0x##n
#define HEX(n)  _HEX(n)

/* Enumeration that is used by the assemble.py and imgtool\main.py scripts
 * for correct binary generation when nested macros are used
 */

enum image_attributes
{
#if (OEMUROT_LOAD_AND_RUN == NO_LOAD_AND_RUN)
  RE_DOWNLOAD_MENU = 0,
#else
  RE_DOWNLOAD_MENU = 1,
#endif /* OEMUROT_LOAD_AND_RUN == NO_LOAD_AND_RUN */
#if defined(MCUBOOT_OVERWRITE_ONLY)
  RE_OVERWRITE = 1,
#else
  RE_OVERWRITE = 0,
#endif /* MCUBOOT_OVERWRITE_ONLY */
  RE_FLASH_AREA_SCRATCH_SIZE = FLASH_AREA_SCRATCH_SIZE,

  RE_APPLI_S_ADDRESS = S_CODE_START + BL2_HEADER_SIZE,
  RE_APPLI_NS_ADDRESS = NS_CODE_START + BL2_HEADER_SIZE,

  RE_DATA_S_ADDRESS = S_DATA_START,
  RE_DATA_NS_ADDRESS = NS_DATA_START,
  RE_DATA_S_SIZE = S_DATA_SIZE,
  RE_DATA_NS_SIZE = NS_DATA_SIZE,

  RE_FLASH_AREA_0_OFFSET = FLASH_AREA_0_OFFSET,
  RE_FLASH_AREA_1_OFFSET = FLASH_AREA_1_OFFSET,
  RE_FLASH_AREA_2_OFFSET = FLASH_AREA_2_OFFSET,
  RE_FLASH_AREA_3_OFFSET = FLASH_AREA_3_OFFSET,
  RE_FLASH_AREA_4_OFFSET = FLASH_AREA_4_OFFSET,
  RE_FLASH_AREA_5_OFFSET = FLASH_AREA_5_OFFSET,

  RE_FLASH_AREA_2_ADDRESS = EXT_FLASH_BASE_ADDRESS + FLASH_AREA_2_OFFSET,
  RE_FLASH_AREA_3_ADDRESS = EXT_FLASH_BASE_ADDRESS + FLASH_AREA_3_OFFSET,

  RE_FLASH_S_PARTITION_SIZE = FLASH_S_PARTITION_SIZE,
  RE_FLASH_NS_PARTITION_SIZE = FLASH_NS_PARTITION_SIZE,
  RE_FLASH_S_DATA_PARTITION_SIZE = FLASH_S_DATA_PARTITION_SIZE,
  RE_FLASH_NS_DATA_PARTITION_SIZE = FLASH_NS_DATA_PARTITION_SIZE,

#if (MCUBOOT_S_DATA_IMAGE_NUMBER == 1)
  RE_S_DATA_IMAGE_NUMBER = 1,
  RE_FLASH_AREA_6_OFFSET = FLASH_AREA_6_OFFSET,
  RE_FLASH_AREA_6_ADDRESS = EXT_FLASH_BASE_ADDRESS + FLASH_AREA_6_OFFSET,
  RE_FLASH_AREA_6_SIZE = FLASH_AREA_6_SIZE,
#else
  RE_S_DATA_IMAGE_NUMBER = 0,
  RE_FLASH_AREA_6_OFFSET = 0,
  RE_FLASH_AREA_6_ADDRESS = 0,
  RE_FLASH_AREA_6_SIZE = 0,
#endif /* MCUBOOT_S_DATA_IMAGE_NUMBER == 1 */

#if (MCUBOOT_NS_DATA_IMAGE_NUMBER == 1)
  RE_NS_DATA_IMAGE_NUMBER = 1,
  RE_FLASH_AREA_7_OFFSET = FLASH_AREA_7_OFFSET,
  RE_FLASH_AREA_7_ADDRESS = EXT_FLASH_BASE_ADDRESS + FLASH_AREA_7_OFFSET,
  RE_FLASH_AREA_7_SIZE = FLASH_AREA_7_SIZE,
  RE_DATA2_NS_ADDRESS = NS_DATA2_START + BL2_HEADER_SIZE,
#else
  RE_NS_DATA_IMAGE_NUMBER = 0,
  RE_FLASH_AREA_7_OFFSET = 0,
  RE_FLASH_AREA_7_ADDRESS = 0,
  RE_FLASH_AREA_7_SIZE = 0,
  RE_DATA2_NS_ADDRESS = 0,
#endif /* MCUBOOT_S_DATA_IMAGE_NUMBER == 1 */
  RE_FLASH_END_SECTOR = FLASH_AREA_END_OFFSET - 1,
};
